import type { Metadata } from "next";

import { Bruno_Ace_SC, Geist, Geist_Mono, Montserrat, Press_Start_2P } from "next/font/google";

import "@workspace/ui/globals.css"
import TanstackProvider from "@/providers/tanstack-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
})

const pressStart = Press_Start_2P({
  weight: "400",
  variable: "--font-press-start",
  subsets: ["latin"]
})

const brunoAce = Bruno_Ace_SC({
  weight: "400",
  variable: "--font-bruno-ace",
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "HHCLOSET",
  // description: "Generated by create next app",
};

export default function RootLayout(props: {
  children: React.ReactNode;
  modal: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        {/* <script type="module" src="https://ajax.googleapis.com/ajax/libs/model-viewer/4.0.0/model-viewer.min.js"></script> */}

      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} ${montserrat.variable} ${pressStart.variable} ${brunoAce.variable} antialiased flex`}>
        <main className="w-full">
          <div className="relative">
            <TanstackProvider>

              {props.children}

            </TanstackProvider>
            {/* <model-viewer
             src={"https://res.cloudinary.com/diedtejt4/raw/upload/v1763395709/3d_models/gxs66xizhphvm8qzd0ne.gltf"}
      alt="3D model"
      auto-rotate
      camera-controls
      ar
      style={{ width: "500px", height: "500px" }}>
              
            </model-viewer> */}
          </div>
        </main>
      </body>
    </html>
  );
}
